(cl:defpackage hobe_rospy_test-msg
  (:use )
  (:export
   "<GRIPPER>"
   "GRIPPER"
   "<MAINSERVICEREQUEST>"
   "MAINSERVICEREQUEST"
   "<MASS>"
   "MASS"
   "<MONITOR>"
   "MONITOR"
   "<MONITORSERVICEREQUEST>"
   "MONITORSERVICEREQUEST"
   "<MONITORSERVICERESPONSE>"
   "MONITORSERVICERESPONSE"
   "<PALLETIZERPACKINGFINISH>"
   "PALLETIZERPACKINGFINISH"
   "<QUERYSERVICEREQUEST>"
   "QUERYSERVICEREQUEST"
   "<QUERYSERVICERESPONSE>"
   "QUERYSERVICERESPONSE"
   "<SERVICERESULT>"
   "SERVICERESULT"
   "<TEMPTEST>"
   "TEMPTEST"
  ))

