
(cl:in-package :asdf)

(defsystem "hobe_rospy_test-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "AABB" :depends-on ("_package_AABB"))
    (:file "_package_AABB" :depends-on ("_package"))
    (:file "Gripper" :depends-on ("_package_Gripper"))
    (:file "_package_Gripper" :depends-on ("_package"))
    (:file "MainServiceRequest" :depends-on ("_package_MainServiceRequest"))
    (:file "_package_MainServiceRequest" :depends-on ("_package"))
    (:file "Mass" :depends-on ("_package_Mass"))
    (:file "_package_Mass" :depends-on ("_package"))
    (:file "Monitor" :depends-on ("_package_Monitor"))
    (:file "_package_Monitor" :depends-on ("_package"))
    (:file "MonitorServiceRequest" :depends-on ("_package_MonitorServiceRequest"))
    (:file "_package_MonitorServiceRequest" :depends-on ("_package"))
    (:file "MonitorServiceResponse" :depends-on ("_package_MonitorServiceResponse"))
    (:file "_package_MonitorServiceResponse" :depends-on ("_package"))
    (:file "PalletizerPackingFinish" :depends-on ("_package_PalletizerPackingFinish"))
    (:file "_package_PalletizerPackingFinish" :depends-on ("_package"))
    (:file "QueryServiceRequest" :depends-on ("_package_QueryServiceRequest"))
    (:file "_package_QueryServiceRequest" :depends-on ("_package"))
    (:file "QueryServiceResponse" :depends-on ("_package_QueryServiceResponse"))
    (:file "_package_QueryServiceResponse" :depends-on ("_package"))
    (:file "ServiceResult" :depends-on ("_package_ServiceResult"))
    (:file "_package_ServiceResult" :depends-on ("_package"))
    (:file "TempTest" :depends-on ("_package_TempTest"))
    (:file "_package_TempTest" :depends-on ("_package"))
  ))