// Generated by gencpp from file hobe_rospy_test/LiftServiceResponse.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICERESPONSE_H
#define HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hobe_rospy_test
{
template <class ContainerAllocator>
struct LiftServiceResponse_
{
  typedef LiftServiceResponse_<ContainerAllocator> Type;

  LiftServiceResponse_()
    : success(false)  {
    }
  LiftServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LiftServiceResponse_

typedef ::hobe_rospy_test::LiftServiceResponse_<std::allocator<void> > LiftServiceResponse;

typedef boost::shared_ptr< ::hobe_rospy_test::LiftServiceResponse > LiftServiceResponsePtr;
typedef boost::shared_ptr< ::hobe_rospy_test::LiftServiceResponse const> LiftServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hobe_rospy_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hobe_rospy_test/LiftServiceResponse";
  }

  static const char* value(const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiftServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hobe_rospy_test::LiftServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICERESPONSE_H
