// Generated by gencpp from file hobe_rospy_test/LiftService.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICE_H
#define HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICE_H

#include <ros/service_traits.h>


#include <hobe_rospy_test/LiftServiceRequest.h>
#include <hobe_rospy_test/LiftServiceResponse.h>


namespace hobe_rospy_test
{

struct LiftService
{

typedef LiftServiceRequest Request;
typedef LiftServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LiftService
} // namespace hobe_rospy_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hobe_rospy_test::LiftService > {
  static const char* value()
  {
    return "51f32333f2c561d5ba412282aada3d3f";
  }

  static const char* value(const ::hobe_rospy_test::LiftService&) { return value(); }
};

template<>
struct DataType< ::hobe_rospy_test::LiftService > {
  static const char* value()
  {
    return "hobe_rospy_test/LiftService";
  }

  static const char* value(const ::hobe_rospy_test::LiftService&) { return value(); }
};


// service_traits::MD5Sum< ::hobe_rospy_test::LiftServiceRequest> should match
// service_traits::MD5Sum< ::hobe_rospy_test::LiftService >
template<>
struct MD5Sum< ::hobe_rospy_test::LiftServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::LiftService >::value();
  }
  static const char* value(const ::hobe_rospy_test::LiftServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::LiftServiceRequest> should match
// service_traits::DataType< ::hobe_rospy_test::LiftService >
template<>
struct DataType< ::hobe_rospy_test::LiftServiceRequest>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::LiftService >::value();
  }
  static const char* value(const ::hobe_rospy_test::LiftServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hobe_rospy_test::LiftServiceResponse> should match
// service_traits::MD5Sum< ::hobe_rospy_test::LiftService >
template<>
struct MD5Sum< ::hobe_rospy_test::LiftServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::LiftService >::value();
  }
  static const char* value(const ::hobe_rospy_test::LiftServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::LiftServiceResponse> should match
// service_traits::DataType< ::hobe_rospy_test::LiftService >
template<>
struct DataType< ::hobe_rospy_test::LiftServiceResponse>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::LiftService >::value();
  }
  static const char* value(const ::hobe_rospy_test::LiftServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_LIFTSERVICE_H
