// Generated by gencpp from file hobe_rospy_test/MoveBackService.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_MOVEBACKSERVICE_H
#define HOBE_ROSPY_TEST_MESSAGE_MOVEBACKSERVICE_H

#include <ros/service_traits.h>


#include <hobe_rospy_test/MoveBackServiceRequest.h>
#include <hobe_rospy_test/MoveBackServiceResponse.h>


namespace hobe_rospy_test
{

struct MoveBackService
{

typedef MoveBackServiceRequest Request;
typedef MoveBackServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBackService
} // namespace hobe_rospy_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hobe_rospy_test::MoveBackService > {
  static const char* value()
  {
    return "e7b883f3f3085a2a026775cc770f647f";
  }

  static const char* value(const ::hobe_rospy_test::MoveBackService&) { return value(); }
};

template<>
struct DataType< ::hobe_rospy_test::MoveBackService > {
  static const char* value()
  {
    return "hobe_rospy_test/MoveBackService";
  }

  static const char* value(const ::hobe_rospy_test::MoveBackService&) { return value(); }
};


// service_traits::MD5Sum< ::hobe_rospy_test::MoveBackServiceRequest> should match
// service_traits::MD5Sum< ::hobe_rospy_test::MoveBackService >
template<>
struct MD5Sum< ::hobe_rospy_test::MoveBackServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::MoveBackService >::value();
  }
  static const char* value(const ::hobe_rospy_test::MoveBackServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::MoveBackServiceRequest> should match
// service_traits::DataType< ::hobe_rospy_test::MoveBackService >
template<>
struct DataType< ::hobe_rospy_test::MoveBackServiceRequest>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::MoveBackService >::value();
  }
  static const char* value(const ::hobe_rospy_test::MoveBackServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hobe_rospy_test::MoveBackServiceResponse> should match
// service_traits::MD5Sum< ::hobe_rospy_test::MoveBackService >
template<>
struct MD5Sum< ::hobe_rospy_test::MoveBackServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::MoveBackService >::value();
  }
  static const char* value(const ::hobe_rospy_test::MoveBackServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::MoveBackServiceResponse> should match
// service_traits::DataType< ::hobe_rospy_test::MoveBackService >
template<>
struct DataType< ::hobe_rospy_test::MoveBackServiceResponse>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::MoveBackService >::value();
  }
  static const char* value(const ::hobe_rospy_test::MoveBackServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_MOVEBACKSERVICE_H
