// Generated by gencpp from file hobe_rospy_test/PalletService.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_PALLETSERVICE_H
#define HOBE_ROSPY_TEST_MESSAGE_PALLETSERVICE_H

#include <ros/service_traits.h>


#include <hobe_rospy_test/PalletServiceRequest.h>
#include <hobe_rospy_test/PalletServiceResponse.h>


namespace hobe_rospy_test
{

struct PalletService
{

typedef PalletServiceRequest Request;
typedef PalletServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PalletService
} // namespace hobe_rospy_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hobe_rospy_test::PalletService > {
  static const char* value()
  {
    return "1b1aad6e6b75c669e52bd93dbc857957";
  }

  static const char* value(const ::hobe_rospy_test::PalletService&) { return value(); }
};

template<>
struct DataType< ::hobe_rospy_test::PalletService > {
  static const char* value()
  {
    return "hobe_rospy_test/PalletService";
  }

  static const char* value(const ::hobe_rospy_test::PalletService&) { return value(); }
};


// service_traits::MD5Sum< ::hobe_rospy_test::PalletServiceRequest> should match
// service_traits::MD5Sum< ::hobe_rospy_test::PalletService >
template<>
struct MD5Sum< ::hobe_rospy_test::PalletServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::PalletService >::value();
  }
  static const char* value(const ::hobe_rospy_test::PalletServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::PalletServiceRequest> should match
// service_traits::DataType< ::hobe_rospy_test::PalletService >
template<>
struct DataType< ::hobe_rospy_test::PalletServiceRequest>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::PalletService >::value();
  }
  static const char* value(const ::hobe_rospy_test::PalletServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hobe_rospy_test::PalletServiceResponse> should match
// service_traits::MD5Sum< ::hobe_rospy_test::PalletService >
template<>
struct MD5Sum< ::hobe_rospy_test::PalletServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hobe_rospy_test::PalletService >::value();
  }
  static const char* value(const ::hobe_rospy_test::PalletServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hobe_rospy_test::PalletServiceResponse> should match
// service_traits::DataType< ::hobe_rospy_test::PalletService >
template<>
struct DataType< ::hobe_rospy_test::PalletServiceResponse>
{
  static const char* value()
  {
    return DataType< ::hobe_rospy_test::PalletService >::value();
  }
  static const char* value(const ::hobe_rospy_test::PalletServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_PALLETSERVICE_H
