// Generated by gencpp from file hobe_rospy_test/PalletizerPackingFinish.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_PALLETIZERPACKINGFINISH_H
#define HOBE_ROSPY_TEST_MESSAGE_PALLETIZERPACKINGFINISH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hobe_rospy_test
{
template <class ContainerAllocator>
struct PalletizerPackingFinish_
{
  typedef PalletizerPackingFinish_<ContainerAllocator> Type;

  PalletizerPackingFinish_()
    : palletizer()
    , node()  {
    }
  PalletizerPackingFinish_(const ContainerAllocator& _alloc)
    : palletizer(_alloc)
    , node(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _palletizer_type;
  _palletizer_type palletizer;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _node_type;
  _node_type node;





  typedef boost::shared_ptr< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> const> ConstPtr;

}; // struct PalletizerPackingFinish_

typedef ::hobe_rospy_test::PalletizerPackingFinish_<std::allocator<void> > PalletizerPackingFinish;

typedef boost::shared_ptr< ::hobe_rospy_test::PalletizerPackingFinish > PalletizerPackingFinishPtr;
typedef boost::shared_ptr< ::hobe_rospy_test::PalletizerPackingFinish const> PalletizerPackingFinishConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator2> & rhs)
{
  return lhs.palletizer == rhs.palletizer &&
    lhs.node == rhs.node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hobe_rospy_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70cfe6a8687ee2fd71c9e786e3742f96";
  }

  static const char* value(const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70cfe6a8687ee2fdULL;
  static const uint64_t static_value2 = 0x71c9e786e3742f96ULL;
};

template<class ContainerAllocator>
struct DataType< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hobe_rospy_test/PalletizerPackingFinish";
  }

  static const char* value(const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string palletizer\n"
"string node\n"
;
  }

  static const char* value(const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.palletizer);
      stream.next(m.node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PalletizerPackingFinish_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hobe_rospy_test::PalletizerPackingFinish_<ContainerAllocator>& v)
  {
    s << indent << "palletizer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.palletizer);
    s << indent << "node: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_PALLETIZERPACKINGFINISH_H
