// Generated by gencpp from file hobe_rospy_test/ServiceResult.msg
// DO NOT EDIT!


#ifndef HOBE_ROSPY_TEST_MESSAGE_SERVICERESULT_H
#define HOBE_ROSPY_TEST_MESSAGE_SERVICERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hobe_rospy_test
{
template <class ContainerAllocator>
struct ServiceResult_
{
  typedef ServiceResult_<ContainerAllocator> Type;

  ServiceResult_()
    : actionID()
    , result(0)  {
    }
  ServiceResult_(const ContainerAllocator& _alloc)
    : actionID(_alloc)
    , result(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _actionID_type;
  _actionID_type actionID;

   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceResult_

typedef ::hobe_rospy_test::ServiceResult_<std::allocator<void> > ServiceResult;

typedef boost::shared_ptr< ::hobe_rospy_test::ServiceResult > ServiceResultPtr;
typedef boost::shared_ptr< ::hobe_rospy_test::ServiceResult const> ServiceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hobe_rospy_test::ServiceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hobe_rospy_test::ServiceResult_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::ServiceResult_<ContainerAllocator2> & rhs)
{
  return lhs.actionID == rhs.actionID &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hobe_rospy_test::ServiceResult_<ContainerAllocator1> & lhs, const ::hobe_rospy_test::ServiceResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hobe_rospy_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23d42b5d30cbaa2e42e14af29c42ba01";
  }

  static const char* value(const ::hobe_rospy_test::ServiceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23d42b5d30cbaa2eULL;
  static const uint64_t static_value2 = 0x42e14af29c42ba01ULL;
};

template<class ContainerAllocator>
struct DataType< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hobe_rospy_test/ServiceResult";
  }

  static const char* value(const ::hobe_rospy_test::ServiceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string actionID\n"
"int64 result\n"
;
  }

  static const char* value(const ::hobe_rospy_test::ServiceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actionID);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hobe_rospy_test::ServiceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hobe_rospy_test::ServiceResult_<ContainerAllocator>& v)
  {
    s << indent << "actionID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.actionID);
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOBE_ROSPY_TEST_MESSAGE_SERVICERESULT_H
